# Generated by Django 2.0.1 on 2018-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paars', '0002_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dysisci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ZO', 'Zonnestraaltje'), ('LI', 'Lid'), ('LU', 'Luna')], default='ZO', max_length=2)),
                ('naam', models.CharField(max_length=60)),
                ('generatie', models.IntegerField()),
                ('studie', models.CharField(max_length=50)),
                ('foto', models.FileField(upload_to='static/img/')),
                ('info', models.TextField()),
            ],
        ),
    ]
